name: Server Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**/*.py'
      - 'server/pyproject.toml'
      - 'server/tests/**/*.py'
      - 'server/pytest.ini'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**/*.py'
      - 'server/pyproject.toml'
      - 'server/tests/**/*.py'
      - 'server/pytest.ini'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.lock

    - name: Run tests with pytest
      run: |
        pytest --cov=src --cov-report=term
